services:
  - type: web
    name: recrutamento-pro
    env: node
    plan: free
    buildCommand: "npm install && npx prisma migrate deploy && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: recrutamento-pro-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://recrutamento-pro.onrender.com"

databases:
  - name: recrutamento-pro-db
    plan: free
    region: oregon
